import React from 'react';
import Sidebar from '../Sidebar';
import FooterBar from '../FooterBar';

const Services = () => {
  return (


    <div className='flex flex-col min-h-screen bg-gray-900'> 
    <div style={{backgroundColor: '#1a365d'}} className='  flex justify-center  fixed top-0 w-full left-1/2 transform -translate-x-1/2'>
  <p className="text-white text-3xl font-bold pt-2  ">SERVICES</p>
</div>
       <Sidebar />
       <div className="flex justify-center items-center mt-8 flex-grow px-4"> 
         <div className="w-full sm:w-3/4 pl-8 mt-2">
            <div className="bg-gray-800 text-white">
              <div className="p-4">
                <div className="mb-8">
                  <h5 className="text-xl font-bold mb-2">CCTV</h5>
                  <p className="text-sm mb-4">We install, service and manage high 
                          quality security CCTV cameras, control 
                          panels, duplex monitors, digital DVR, 
                          and power back-up systems. We supply 
                          and install IP, PTZ and Analogy HD 
                          cameras for indoor and outdoor with 
                          night vision infrared, motion sensitive 
                          and miniature spy cameras</p>
                  <img src="images/cctv.jpeg" alt="cctv" className="w-200 h-32 border border-green-500 object-cover mt-4" />
                </div>
                <div className="mb-8">
                  <h5 className="text-xl font-bold mb-2">Alarms</h5>
                  <p className="text-sm mb-4">
                            We offer state of the art security alarm system with modern encrypting and signal to our base station that in return alerts our nearest patrol team for rapid response. We deal in the following categories of Alarm:
                          </p>
                          <ul className="list-disc pl-6 mb-4">
                            <li>Panic Alarm</li>
                            <li>Intruder/Automatic Alarm</li>
                            <li>Fire Alarm</li>
                          </ul>

                  <img src="images/alarm.jpeg" alt="alrm" className="w-200 h-32 border border-green-500 object-cover mt-4" />
                </div> 
                <div className="mb-8">
                  <h5 className="text-xl font-bold mb-2">Electric Fencing</h5>
                  <p className="text-sm mb-4">We install and service electric fences 
                            which is a barrier that uses electric 
                            shocks to deter intrusion. 
                            The high voltage generated by energizer 
                            machine may have effects ranging from 
                            discomfort to death</p>
                  <img src="images/securityWire.jpeg" alt="securty" className="w-200 h-32 border border-green-500 object-cover mt-4" />
                </div> 
                <div className="mb-8">
                  <h5 className="text-xl font-bold mb-2">Car Tracking</h5>
                  <p className="text-sm mb-4">We install and service electric fences 
                                    which is a barrier that uses electric 
                                    shocks to deter intrusion. 
                                    The high voltage generated by energizer 
                                    machine may have effects ranging from 
                                    discomfort to death
                                    We specialize in installing tracking 
                                    devices and real time tracking of 
                                    vehicles, motorbikes etc. using a wide 
                                    range of technology including Google, 
                                    satellite OSM and I track app</p>
                  <img src="images/tracker.jpeg" alt="tarckwr" className="w-200 h-32 border border-green-500 object-cover mt-4" />
                </div>

                <div className="mb-8">
                  <h5 className="text-xl font-bold mb-2">SECURITY APPARATUS</h5>
                  <p className="text-sm mb-4">We specialize in supply, installation and
                                 servicing various security apparatus e.g.,</p>
                                 <ul className="list-disc pl-6 mb-4">
                            <li>Fire extinguisher</li>
                            <li>Smoke detectors</li>
                            <li>Finger scanners,CCTV, doorbells</li>
                            <li>Intelligent camera bulbs</li>
                            <li>Access control systems and other safety equipment</li>
                          </ul>
                  <img src="images/fireExtinguisher.jpeg" alt="fire" className="w-200 h-32 border border-green-500 object-cover mt-4" />
                </div>

                <div className="mb-8">
                  <h5 className="text-xl font-bold mb-2">PRIVATE INVESTIGATIONS</h5>
                  <p className="text-sm mb-4">We have well trained and experienced
                                          expert personnel capable of handling
                                          investigations and evidence
                                          preservations ranging from:</p>
                         <ul className="list-disc pl-6 mb-4">
                            <li>Financial and fraud investigations.</li>
                            <li>Criminal investigations.</li>
                            <li>Forensic evidence extraction,</li>
                            <li>preservation, and presentation.</li>
                            <li>Crime scene management.</li>
                            <li>Insurance investigations.</li>
                            <li>Property tracking.</li>
                          </ul>
                   <img src="images/investigation.jpeg" alt="investigation" className="w-200 h-32 border border-green-500 object-cover mt-4" />
                </div>

                <div className="mb-8">
                  <h5 className="text-xl font-bold mb-2">COURIER SERVICES</h5>
                  <p className="text-sm mb-4">Ottoman provides timely and
                            efficient delivery across Western
                            Kenya Region. We are one of
                            the most trusted courier service
                            companies offering you the
                            best service in your time</p> 
                   <img src="images/motorBike.jpeg" alt="motor" className="w-200 h-32 border border-green-500 object-cover mt-4" />
                </div>
                {/* Add other services similarly */}

              </div>
            </div>
          </div>
        </div> 
      <FooterBar /></div>
     );
}

export default Services;
